name: Push Code to GitHub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Git
        run: |
          git config --global user.email "admin@elite-artists.com"
          git config --global user.name "Elite Artists"

      - name: Add Changes
        run: git add .

      - name: Commit Changes
        run: git commit -m "Add code changes"

      - name: - Call OpenAI API

        run: |
          # Replace this placeholder command with your actual command to call the OpenAI API
          # Example command:
          # curl -X POST -H "Authorization: Bearer sk-iqYgrQ2BpwyD2hhuwTEsT3BlbkFJC9esIkZmRZWFJ6s0sa6I" -H "Content-Type: application/json" -d '{"text": "Your text here"}' https://api.openai.com/v1/complete

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
